-- LLAVE MAESTRA: Desactivar reglas de conexión temporalmente
PRAGMA foreign_keys = OFF;

-- 1. Limpieza segura
DROP TABLE IF EXISTS productos;

-- 2. Crear la tabla
CREATE TABLE productos (
    id INTEGER PRIMARY  KEY,
    nombre TEXT NOT NULL,
    precio_venta INTEGER NOT NULL,
    categoria TEXT NOT NULL,
    descripcion TEXT
);

-- 3. Inserción de todos los productos
INSERT INTO productos (id, nombre, precio_venta, categoria, descripcion) VALUES 
(1, 'FULL CHICKEN (40 Piezas)', 20990, 'Tablas', 'Pollo, Queso Cream, Cebollín, Palta, Panko, Niguiri Crispy'),
(2, 'TABLA 2 (38 Piezas)', 18990, 'Tablas', 'Avo Sake, Maki Kani, Hoso Ebi, Chicken Panko, Pollo Panko, Salmon Panko'),
(3, 'TABLA 3 (72 Piezas)', 30990, 'Tablas', 'Avo Sake, Maki Kani, Cream Chicken, Futo Sake, Hoso Ebi, Chicken Panko, Vegetal Panko, Pollo Panko, Salmon Panko'),
(4, 'TABLA LIKE (50 Piezas)', 21990, 'Tablas', 'California Kani, Avo Chicken, Hoso Chicken Panko, Cream Vegetal, Vegetal Panko, Pollo Panko'),
(5, 'TABLA HOT (34 Piezas)', 19990, 'Tablas', 'Ebi Panko, Vegetal Panko, Hoso Chicken Panko, Pollo Panko'),
(6, 'TABLA VEGAN (32 Piezas)', 16990, 'Tablas', 'California Vegetal, Vegan Panko, Avo Fresh, Ura Vegan'),
(7, 'SUPER 1 (30 piezas)', 14990, 'Super Promos', 'Pollo Teriyaki, Kanikama, Camarón. Incluye soya, unagui y palitos.'),
(8, 'SUPER 2 (50 piezas)', 19990, 'Super Promos', 'Pollo Teriyaki, Kanikama, Camarón, Palta. Incluye soya, unagui y palitos.'),
(9, 'SUPER 3 (70 piezas)', 27990, 'Super Promos', 'Pollo Teriyaki, Kanikama, Palmito, Camarón, Palta. Incluye soya, unagui y palitos.'),
(10, 'KANI PANKO', 5300, 'Rolls - Tempura/Panko', 'Kanikama - Queso Cream - Pimentón'),
(11, 'CHICKEN PANKO', 5800, 'Rolls - Tempura/Panko', 'Pollo Teriyaki - Queso Cream - Cebollín'),
(12, 'SAKE PANKO', 6300, 'Rolls - Tempura/Panko', 'Salmón - Queso Cream - Ciboulette'),
(13, 'EBI PANKO', 5900, 'Rolls - Tempura/Panko', 'Camarón - Queso Cream - Cebollín'),
(14, 'TAKO PANKO', 6500, 'Rolls - Tempura/Panko', 'Pulpo - Queso Cream - Ciboulette'),
(15, 'VEGETAL PANKO', 5400, 'Rolls - Tempura/Panko', 'Espárrago - Pimentón - Palta'),
(16, 'SMOKE PANKO', 5900, 'Rolls - Tempura/Panko', 'Salmón Ahumado - Queso Cream - Cebollín'),
(17, 'MIX PANKO', 6500, 'Rolls - Tempura/Panko', 'Camarón - Salmón - Queso Cream - Cebollín'),
(18, 'VEGAN PANKO', 5500, 'Rolls - Tempura/Panko', 'Palta - Tomate Cherry - Choclo Baby'),
(19, 'CHICKEN NUSS PANKO', 6100, 'Rolls - Tempura/Panko', 'Pollo Teriyaki - Queso Cream - Nueces/Almendras'),
(20, 'EBI PANKO 2.0', 6300, 'Rolls - Tempura/Panko', 'Camarón - Queso Cream - Palta'),
(21, 'SEA BOMB', 7400, 'Rolls - Tempura/Panko', 'Camarón - Salmón - Pulpo - Queso Cream - Ciboulette'),
(22, 'CHICKEN PANKO 2.0', 6200, 'Rolls - Tempura/Panko', 'Pollo Teriyaki - Queso Cream - Palta'),
(23, 'MAGURO PANKO', 6400, 'Rolls - Tempura/Panko', 'Atún - Queso Cream - Cebollín'),
(24, 'PANKO ACEVICHADO', 9500, 'Rolls - Tempura/Panko', 'Queso Cream - Palta'),
(25, 'AVO KANI', 5400, 'Rolls - Avocado', 'Kanikama - Queso Cream - Cebollín'),
(26, 'AVO CHICKEN', 6200, 'Rolls - Avocado', 'Pollo Teriyaki - Queso Cream - Cebollín'),
(27, 'AVO SAKE', 6500, 'Rolls - Avocado', 'Salmón - Queso Cream - Ciboulette'),
(28, 'AVO EBI', 6400, 'Rolls - Avocado', 'Camarón - Queso Cream - Cebollín'),
(29, 'TAKO ROLL', 6600, 'Rolls - Avocado', 'Pulpo - Queso Cream - Cebollín'),
(30, 'AVO FRESH', 5200, 'Rolls - Avocado', 'Palmito - Espárrago - Cebollín'),
(31, 'TERI PANKO', 6500, 'Rolls - Avocado', 'Pollo Panko - Queso Cream - Cebollín'),
(32, 'AVO SAKE PANKO', 6900, 'Rolls - Avocado', 'Salmón Panko - Queso Cream - Cebollín'),
(33, 'AVO EBI TEMPURA', 6700, 'Rolls - Avocado', 'Camarón Tempura - Queso Cream - Ciboulette'),
(34, 'AVO SMOKE ROLL', 6200, 'Rolls - Avocado', 'Salmón Ahumado - Queso Cream - Cebollín'),
(35, 'AVO MIX', 7200, 'Rolls - Avocado', 'Salmón - Camarón - Queso Cream - Cebollín'),
(36, 'AVO TROPICAL', 6600, 'Rolls - Avocado', 'Salmón - Mango'),
(37, 'EBI LIKE', 6200, 'Rolls - Avocado', 'Camarón - Queso Cream - Masago'),
(38, 'AVO TONNO', 6400, 'Rolls - Avocado', 'Atún - Queso Cream - Cebollín'),
(39, 'AVO LIKE ROLL', 6300, 'Rolls - Avocado', 'Salmón - Palmito - Espárrago'),
(40, 'AVO VEGETAL PANKO', 5400, 'Rolls - Avocado', 'Cebollín Panko - Queso Cream - Pimentón'),
(41, 'AVO ACEVICHADO', 9100, 'Rolls - Avocado', 'Queso Cream - Espárrago - Palmito'),
(42, 'CALIFORNIA KANI', 4400, 'Rolls - Uramaki', 'Kanikama - Palta'),
(43, 'CALIFORNIA CHICKEN', 4800, 'Rolls - Uramaki', 'Pollo Teriyaki - Palta'),
(44, 'CALIFORNIA SAKE', 5300, 'Rolls - Uramaki', 'Salmón - Palta'),
(45, 'CALIFORNIA EBI', 4900, 'Rolls - Uramaki', 'Camarón - Palta'),
(46, 'CALIFORNIA VEGETAL', 4700, 'Rolls - Uramaki', 'Palmito - Palta - Ciboulette - Espárrago'),
(47, 'MAKI EBI TEMPURA', 5900, 'Rolls - Uramaki', 'Camarón Tempura - Queso Cream - Ciboulette'),
(48, 'MAKI YAKI PANKO', 5500, 'Rolls - Uramaki', 'Pollo Panko - Queso Cream - Cebollín'),
(49, 'MAKI SAKE PANKO', 5900, 'Rolls - Uramaki', 'Salmón Panko - Queso Cream - Cebollín'),
(50, 'SMOKE MAKI', 5200, 'Rolls - Uramaki', 'Salmón Ahumado - Queso Cream - Cebollín'),
(51, 'MAKI KANI', 4700, 'Rolls - Uramaki', 'Kanikama - Queso Cream - Palta'),
(52, 'MAKI YAKI', 5300, 'Rolls - Uramaki', 'Pollo Teriyaki - Queso Cream - Palta'),
(53, 'SAKE MAKI', 5700, 'Rolls - Uramaki', 'Salmón - Queso Cream - Palta'),
(54, 'EBI MAKI', 5400, 'Rolls - Uramaki', 'Camarón - Queso Cream - Palta - Ciboulette'),
(55, 'TAKO MAKI ROLL', 5900, 'Rolls - Uramaki', 'Pulpo - Palta - Ciboulette'),
(56, 'EBI SPICY', 5000, 'Rolls - Uramaki', 'Camarón - Palta - Ciboulette - Sriracha'),
(57, 'MAGURO MAKI', 5500, 'Rolls - Uramaki', 'Atún - Palta - Ciboulette'),
(58, 'URA VEGAN', 4400, 'Rolls - Uramaki', 'Palta - Pepino - Cebollín'),
(59, 'URA ACEVICHADO', 8500, 'Rolls - Uramaki', 'Queso Cream - Palmito - Palta'),
(60, 'CREAM KANI', 5000, 'Rolls - Cream', 'Kanikama - Palta'),
(61, 'CREAM CHICKEN', 5600, 'Rolls - Cream', 'Pollo Teriyaki - Palta - Cebollín'),
(62, 'CREAM SAKE', 6200, 'Rolls - Cream', 'Salmón - Palta - Ciboulette'),
(63, 'CREAM EBI', 5800, 'Rolls - Cream', 'Camarón - Ciboulette - Palta'),
(64, 'TAKO SNOW', 6300, 'Rolls - Cream', 'Pulpo - Palta - Pimentón'),
(65, 'SNOW EBI PANKO', 6300, 'Rolls - Cream', 'Camarón Panko - Palta - Cebollín'),
(66, 'SNOW SAKE TEMPURA', 6400, 'Rolls - Cream', 'Salmón Tempura - Espárrago - Pimentón'),
(67, 'SNOW YAKI PANKO', 6100, 'Rolls - Cream', 'Pollo Panko - Palta - Cebollín'),
(68, 'SNOW TROPICAL', 6400, 'Rolls - Cream', 'Camarón Panko - Mango'),
(69, 'CREAM CHILI', 6000, 'Rolls - Cream', 'Salmón - Coco/Merken - Pimentón - Cebollín'),
(70, 'SNOW MIX', 6000, 'Rolls - Cream', 'Camarón - Salmón - Palta - Cebollín'),
(71, 'CREAM SMOKE', 5700, 'Rolls - Cream', 'Salmón Ahumado - Palta - Cebollín'),
(72, 'CREAM LIKE', 5500, 'Rolls - Cream', 'Masago - Palmito - Palta'),
(73, 'CREAM VEGETAL', 5000, 'Rolls - Cream', 'Palmito - Espárrago - Cebollín'),
(74, 'CREAM VEGETAL PANKO', 5100, 'Rolls - Cream', 'Cebollín Panko - Palta - Pimentón'),
(75, 'TUNA CREAM', 6100, 'Rolls - Cream', 'Atún - Palta - Palmito'),
(76, 'CREAM ACEVICHADO', 8900, 'Rolls - Cream', 'Palta - Espárrago - Palmito'),
(77, 'SAKE KANI', 5900, 'Rolls - Sake', 'Kanikama - Palta - Ciboulette'),
(78, 'SAKE EBI ROLL', 6400, 'Rolls - Sake', 'Camarón - Queso Cream - Masago'),
(79, 'SAKE TAKO', 7000, 'Rolls - Sake', 'Pulpo - Queso Cream - Cebollín'),
(80, 'GARDEN SAKE', 5800, 'Rolls - Sake', 'Palmito - Espárrago - Palta'),
(81, 'SAKE SMOKE', 6500, 'Rolls - Sake', 'Salmón Ahumado - Queso Cream - Palta'),
(82, 'SAKE EBI PANKO', 6900, 'Rolls - Sake', 'Camarón Panko - Queso Cream - Cebollín'),
(83, 'SAKE ACEVICHADO', 9200, 'Rolls - Sake', 'Queso Cream - Palta - Palmito'),
(84, 'SAKE VEGETAL PANKO', 5900, 'Rolls - Sake', 'Cebollín Panko - Queso Cream - Espárrago'),
(85, 'Sin Arroz Opción 1', 7900, 'Sin Arroz', 'Salmón - Camarón - Queso Cream - Cebollín - Choclo Baby Panko'),
(86, 'Sin Arroz Opción 2', 7500, 'Sin Arroz', 'Pollo Panko - Palta - Palmito - Cebollín - Pimentón'),
(87, 'Sin Arroz Opción 3', 8000, 'Sin Arroz', 'Camarón Panko - Queso Cream - Masago - Palta - Cebollín'),
(88, 'Sin Arroz Opción 4', 7600, 'Sin Arroz', 'Pollo Teriyaki - Palta - Nueces - Almendras - Queso Cream - Cebollín'),
(89, 'Sin Arroz Opción 5', 8100, 'Sin Arroz', 'Camarón - Salmón - Queso Cream - Palta - Cebollín'),
(90, 'HOSO KANI', 3200, 'Hosomaki', 'Kanikama - Palta'),
(91, 'HOSO CHICKEN', 3600, 'Hosomaki', 'Pollo Teriyaki - Queso Cream - Cebollín'),
(92, 'HOSO SAKE', 3900, 'Hosomaki', 'Salmón - Queso Cream'),
(93, 'HOSO EBI', 3700, 'Hosomaki', 'Camarón - Queso Cream - Ciboulette'),
(94, 'HOSO TAKO', 4400, 'Hosomaki', 'Pulpo - Queso Cream - Cebollín'),
(95, 'HOSO SMOKE', 3800, 'Hosomaki', 'Salmón Ahumado - Palta - Ciboulette'),
(96, 'HOSO VEGETAL', 3100, 'Hosomaki', 'Palmito - Espárrago'),
(97, 'HOSO TON', 4100, 'Hosomaki', 'Atún - Palta'),
(98, 'FUTO KANI', 5800, 'Futomaki', 'Kanikama - Palta - Pepino - Masago - Cebollín'),
(99, 'FUTO CHICKEN', 6500, 'Futomaki', 'Pollo Teriyaki - Queso Cream - Palta - Pimentón - Ciboulette'),
(100, 'FUTO SAKE', 6800, 'Futomaki', 'Salmón - Palmito - Palta - Cebollín - Pimentón'),
(101, 'FUTO EBI', 6600, 'Futomaki', 'Camarón - Queso Cream - Masago - Palta - Ciboulette'),
(102, 'FUTO TAKO', 6900, 'Futomaki', 'Pulpo - Queso Cream - Palta - Cebollín - Pimentón'),
(103, 'FUTO MIX', 7000, 'Futomaki', 'Salmón - Camarón - Palta - Queso Cream - Cebollín'),
(104, 'FUTO ACEVICHADO', 9000, 'Futomaki', 'Queso Cream - Masago - Palta - Palmito'),
(105, 'FUTO SMOKE', 6400, 'Futomaki', 'Salmón Ahumado - Palta - Pimentón - Ciboulette - Espárrago'),
(106, 'FUTO VEGETAL PANKO', 5700, 'Futomaki', 'Cebollín Panko - Queso Cream - Espárrago - Pimentón - Ciboulette'),
(107, 'LIKE EBI TEMPURA', 5800, 'Special Rolls', 'Camarón - Queso Cream - Ciboulette'),
(108, 'LIKE URA EBI', 6300, 'Special Rolls', 'Camarón Tempura - Queso Cream - Pimentón'),
(109, 'HOSO CHICKEN PANKO', 6000, 'Special Rolls', 'Pollo Teriyaki - Queso Cream - Cebollín'),
(110, 'MAKI GRAY ROLL', 4500, 'Special Rolls', 'Queso Cream - Palta - Pepino'),
(111, 'ARMY SMOKE ROLL', 5300, 'Special Rolls', 'Salmón Ahumado - Queso Cream - Palta'),
(112, 'LIKE EBI AVO', 6200, 'Special Rolls', 'Camarón - Queso Cream - Palmito'),
(113, 'HOSO NUSS', 4000, 'Special Rolls', 'Queso Cream - Nueces/Almendra'),
(114, 'LIKE AVO CHICKEN', 6500, 'Special Rolls', 'Pollo Teriyaki - Queso Cream - Palmito'),
(115, 'GREEN TONNO FURAI', 6200, 'Special Rolls', 'Atún Panko - Queso Cream'),
(116, 'EBI RAINBOW', 8000, 'Special Rolls', 'Camarón Panko - Queso Cream - Cebollín'),
(117, 'SAKE EBI GRILL', 6500, 'Special Rolls', 'Camarón - Queso Cream - Cebollín'),
(118, 'COCO TEMPURA', 6500, 'Special Rolls', 'Salmón - Queso Cream - Pimentón'),
(119, 'GREEN MIX', 6400, 'Special Rolls', 'Salmón - Camarón - Queso Cream'),
(120, 'CHICKEN CRISPY NUSS', 7400, 'Special Rolls', 'Pollo Teriyaki - Queso Cream Panko - Ciboulette'),
(121, 'Gohan Mixto', 6990, 'Arroz Gohan', NULL),
(122, 'Gohan Mixto Panko', 7990, 'Arroz Gohan', NULL),
(123, 'Gohan Pollo', 6990, 'Arroz Gohan', NULL),
(124, 'Gohan Pollo Panko', 7990, 'Arroz Gohan', NULL),
(125, 'Gohan Vegetal', 5490, 'Arroz Gohan', NULL),
(126, 'Handroll Pollo', 4500, 'Handroll', 'Pollo - Queso - Cebolllín'),
(127, 'Handroll Camarón', 4800, 'Handroll', 'Camarón - Queso - Cebolllín'),
(128, 'Handroll Vegetal', 4300, 'Handroll', 'Verduras - Palmito - Palta - Cebollín'),
(129, 'Burger Pollo', 7490, 'Sushi Burger', 'Pollo - Queso - Palta - Cebolllín - Panko'),
(130, 'Burger Camarón', 7990, 'Sushi Burger', 'Camarón - Queso - Palta - Cebolllín - Panko'),
(131, 'Burger Salmón', 8490, 'Sushi Burger', 'Salmón - Queso - Palta - Cebolllín - Panko'),
(132, 'Sashimi de Salmón (3 Cortes)', 2800, 'Sashimis', NULL),
(133, 'Sashimi de Salmón (6 Cortes)', 5000, 'Sashimis', NULL),
(134, 'Sashimi de Salmón (12 Cortes)', 9000, 'Sashimis', NULL),
(135, 'Sashimi de Pulpo (3 Cortes)', 3400, 'Sashimis', NULL),
(136, 'Sashimi de Pulpo (6 Cortes)', 6000, 'Sashimis', NULL),
(137, 'Sashimi de Pulpo (12 Cortes)', 10500, 'Sashimis', NULL),
(138, 'Nigiri de Salmón (1 Unidad)', 1000, 'Nigiris', NULL),
(139, 'Nigiri de Camarón (1 Unidad)', 1000, 'Nigiris', NULL),
(140, 'Nigiri de Kanikama (1 Unidad)', 900, 'Nigiris', NULL),
(141, 'Nigiris Crispy Pollo (4 Unidades)', 4790, 'Nigiris Crispy', 'Arroz - Pollo - Queso Cream - Cebollín'),
(142, 'Nigiris Crispy Camarón (4 Unidades)', 4990, 'Nigiris Crispy', 'Arroz - Camarón - Queso Cream - Cebollín'),
(143, 'Salmón Panko (3 Unidades)', 3000, 'Snack Tempurizados', NULL),
(144, 'Salmón Panko (6 Unidades)', 5500, 'Snack Tempurizados', NULL),
(145, 'Salmón Panko (12 Unidades)', 9900, 'Snack Tempurizados', NULL),
(146, 'Ebi Temp. (3 Unidades)', 2900, 'Snack Tempurizados', NULL),
(147, 'Ebi Temp. (6 Unidades)', 5400, 'Snack Tempurizados', NULL),
(148, 'Ebi Temp. (12 Unidades)', 9800, 'Snack Tempurizados', NULL),
(149, 'Pollo Panko (3 Unidades)', 2800, 'Snack Tempurizados', NULL),
(150, 'Pollo Panko (6 Unidades)', 4900, 'Snack Tempurizados', NULL),
(151, 'Pollo Panko (12 Unidades)', 9000, 'Snack Tempurizados', NULL),
(152, 'Verduras Temp. (3 Unidades)', 2000, 'Snack Tempurizados', NULL),
(153, 'Verduras Temp. (6 Unidades)', 3600, 'Snack Tempurizados', NULL),
(154, 'Verduras Temp. (12 Unidades)', 6800, 'Snack Tempurizados', NULL),
(155, 'Envoltura Ciboulette', 500, 'Salsas y Extras', NULL),
(156, 'Palitos', 150, 'Salsas y Extras', NULL),
(157, 'Wasabi', 400, 'Salsas y Extras', NULL),
(158, 'Sriracha', 500, 'Salsas y Extras', NULL),
(159, 'Hoja de arroz', 500, 'Salsas y Extras', NULL),
(160, 'Ayuda Palitos', 400, 'Salsas y Extras', NULL),
(161, 'Jengibre', 400, 'Salsas y Extras', NULL),
(162, 'Salsa Unagui', 900, 'Salsas y Extras', NULL),
(163, 'Salsa Soya', 500, 'Salsas y Extras', NULL),
(164, 'Coca-Cola Original 1.5L', 3000, 'Bebidas', '1.5 Litros'),
(165, 'Coca-Cola Zero 1.5L', 3000, 'Bebidas', '1.5 Litros');

-- Reactivar reglas de conexión
PRAGMA foreign_keys = ON;